ERC1155 Mints and Burns
MetricsDAO/harmony_dbt pull request #129
Opened 2022-06-11 08:26 UTC by geewynn

# Description

Closes #121 

# Tests

- [x] Please provide evidence of your successful `dbt run` / `dbt test` here
```
root@5c36fc92c50e:/harmony# dbt run --select erc1155_mint_burn_count
Running with dbt=0.21.1
Found 46 models, 394 tests, 0 snapshots, 0 analyses, 182 macros, 0 operations, 10 seed files, 21 sources, 0 exposures

08:14:54 | Concurrency: 4 threads (target='dev')
08:14:54 | 
08:14:54 | 1 of 1 START table model DEV.erc1155_mint_burn_count................. [RUN]
08:15:05 | 1 of 1 OK created table model DEV.erc1155_mint_burn_count............ [SUCCESS 1 in 11.47s]
08:15:05 | 
08:15:05 | Finished running 1 table model in 47.25s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
root@5c36fc92c50e:/harmony# dbt test --select erc1155_mint_burn_count
Running with dbt=0.21.1
Found 46 models, 394 tests, 0 snapshots, 0 analyses, 182 macros, 0 operations, 10 seed files, 21 sources, 0 exposures

08:16:31 | Concurrency: 4 threads (target='dev')
08:16:31 | 
08:16:31 | 1 of 3 START test not_null_erc1155_mint_burn_count_daily_count....... [RUN]
08:16:31 | 2 of 3 START test not_null_erc1155_mint_burn_count_day_date.......... [RUN]
08:16:31 | 3 of 3 START test not_null_erc1155_mint_burn_count_event............. [RUN]
08:16:34 | 1 of 3 PASS not_null_erc1155_mint_burn_count_daily_count............. [PASS in 3.11s]
08:16:34 | 2 of 3 PASS not_null_erc1155_mint_burn_count_day_date................ [PASS in 3.19s]
08:16:34 | 3 of 3 PASS not_null_erc1155_mint_burn_count_event................... [PASS in 3.64s]
08:16:34 | 
08:16:34 | Finished running 3 tests in 6.92s.

Completed successfully

Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
```
- [x] Any comparison between `prod` and `dev` for any schema change

# Checklist

- [x] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [x] Tag the person(s) responsible for reviewing proposed changes
- [ ] Notes to deployment, if a `full-refresh` is needed for any table
- [x] Run `dbt docs generate` to update the documentation files if this PR is changing the models in any way.

2022-06-11 10:03 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +        cluster_by=['day_date']
add `incremental_strategy = 'delete+insert',`

2022-06-11 10:03 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +        materialized='table',
should be a incremental table

2022-06-11 10:03 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +where f.value='0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62' and event_name ='TransferSingle'
add incremental logic and extract it out from logs

2022-06-11 10:04 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +select * from final
add additional line to end of file

2022-06-11 10:05 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +    event_name,
should also need the evm_address of which contract that is being burnt or minted

2022-06-11 10:06 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +where mint='0x0000000000000000000000000000000000000000'
try to use topics instead of events_input

2022-06-11 10:06 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +group by 1,2
try to use topics instead of events_input

2022-06-11 10:07 UTC, antonyip commented on models/metrics/erc1155_mint_burn_count.sql
> +select * from burn
please install and use dbt formatterhttps://github.com/henriblancke/vscode-dbt-formatter

2022-06-11 10:07 UTC, antonyip requested changes
please fix required changes

2022-06-11 12:55 UTC, antonyip commented on models/metrics/metric_erc1155_mint_burn_count.sql
> +        unique_key=['day_date'],
```suggestion
        unique_key=['day_date','evm_contract_address'],
```
test this, not sure if it will work.

2022-06-11 12:55 UTC, antonyip commented on models/metrics/metric_erc1155_mint_burn_count.sql
> +select * from final
add new line to the file.
also need to use the dbt formatter

2022-06-11 12:55 UTC, antonyip commented on models/metrics/metric_erc1155_mint_burn_count.yml
> +    description: "The daily mint and burn for each erc20 token"
please update documentation

2022-06-11 13:44 UTC, geewynn commented on models/metrics/metric_erc1155_mint_burn_count.sql
> +        unique_key=['day_date'],
this also works

2022-06-23 22:57 UTC, antonyip approved these changes

2022-06-23 22:57 UTC, merged