Create DFK seed liquidity actions table
MetricsDAO/harmony_dbt pull request #96
Opened 2022-04-16 16:46 UTC by D0R11

# Description

Builds the Seed Liquidity Actions table for DFK.

# Test

Here's the sample output running in locally:

```16:45:01 | Concurrency: 4 threads (target='dev')
16:45:01 | 
16:45:01 | 1 of 1 START incremental model DEV.dfk_seed_liquidity_actions........ [RUN]
16:45:11 | 1 of 1 OK created incremental model DEV.dfk_seed_liquidity_actions... [SUCCESS 1 in 9.48s]
16:45:11 | 
16:45:11 | Finished running 1 incremental model in 15.48s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1```

2022-04-23 01:09 UTC, antonyip commented
Hello @D0R11, please follow the style guide located here: https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md

2022-04-24 10:00 UTC, D0R11 commented
Apologies @antonyip, applied the changes now. Kindly check if you have the time. Thank you.

2022-04-24 10:08 UTC, antonyip commented on models/dfk/dfk_seed_liquidity_actions.sql
> +    where 1=1
remove 1=1

2022-04-24 10:08 UTC, antonyip commented on models/dfk/dfk_seed_liquidity_actions.sql
> +        cluster_by=['log_id']
cluster by block_timestamp

2022-04-24 10:08 UTC, antonyip commented on models/dfk/dfk_seed_liquidity_actions.sql
> +            in ('0x02751cec','0xf305d719','0xbaa2abde','0xe8e33700')
leave a comment on what these function signatures are

2022-04-24 10:09 UTC, antonyip commented on models/dfk/dfk_seed_liquidity_actions.sql
> +        and to_address = '0x24ad62502d1c652cc7684081169d04896ac20f30'
leave a comment on what this address is

2022-04-24 10:09 UTC, antonyip requested changes
some minor changes and we're good to go

2022-04-25 14:36 UTC, D0R11 commented
Applied the latest changes

2022-04-25 21:59 UTC, antonyip commented on models/dfk/dfk_seed_liquidity_actions.sql
>          and tx_hash in (select tx_hash from txs)
If you remove the where, it becomes an invalid sql..

2022-04-26 14:23 UTC, D0R11 commented on models/dfk/dfk_seed_liquidity_actions.sql
>          and tx_hash in (select tx_hash from txs)
Apologies! Added the where clause back

2022-05-06 22:36 UTC, antonyip approved these changes
Looks good to me.
Follow up Issues: https://github.com/MetricsDAO/harmony_dbt/issues/110

2022-05-06 22:37 UTC, merged